# --- Core Google Services ---
product/app/Duo                                              # Video calls
product/app/GoogleCalendarSyncAdapter                        # For calendar

product/priv-app/GmsCore                                     # GMS core
product/priv-app/Phonesky                                    # Google Play
product/priv-app/Velvet                                      # Google Search
product/priv-app/GoogleRestore                               # Google Restore
product/priv-app/GooglePartnerSetup                          # Google Partner Setup
product/priv-app/GoogleOneTimeInitializer                    # Google One Time Initializer
product/priv-app/AndroidAutoStub                             # Android Auto Stub
product/priv-app/FamilyLinkParentalControls                  # Family Link
product/priv-app/HotwordEnrollmentXGoogleEx6_WIDEBAND_SMALL  #Hotword Enrollment
product/priv-app/Messages                                    # Messages

system/system/priv-app/GooglePackageInstaller                # Replace with standard or microG
system/system/priv-app/NetworkStackGoogle                    # Google's network metrics (keep NetworkStack)
system/system/priv-app/NSFusedLocation_v6.0                  # Google-based location fusion
system/system/priv-app/DocumentsUIGoogle                     # Files app by Google (use Samsung MyFiles instead)

system_ext/priv-app/GoogleServicesFramework                  # GSF
system_ext/priv-app/GoogleFeedback                           # Google Feedback
system_ext/priv-app/SetupWizard                              # Setup Wizard
system_ext/priv-app/AvatarPicker                             # Avatar Picker

# --- Spyware & Telemetry ---
product/app/com.google.mainline.telemetry                    # Telemetry collector
product/app/com.google.mainline.adservices                   # Adservices
product/app/GoogleLocationHistory                            # Collects location
product/app/AssistantShell                                   # Google Assistant, which means the microphone is always active
product/app/BardShell                                        # Neural Network (Gemini/Bard)

product/priv-app/Turbo                                       # Monitors how and when u use applications
product/priv-app/AndroidSystemIntelligence                   # Intelligence
product/priv-app/PrivateComputeServices                      # Private Compute Services

system/system/app/CaptivePortalLoginGoogle                   # Captive Portal Login Google
system/system/app/GoogleExtShared                            # Google Ext Shared
system/system/app/GooglePrintRecommendationService           # Google Print Recommendation Service

# --- Heavy Apps ---
product/app/YouTube                                          # YouTube
product/app/Chrome64                                         # Google Chrome
product/app/Maps                                             # Google Maps
product/app/Photos                                           # Google Photos
product/app/Gmail2                                           # Gmail
product/app/SpeechServicesByGoogle                           # Speech Service
product/app/TrichromeLibrary64                               # Trichrome Library

system/system/app/ChromeCustomizations                       # Chrome Customizations
